### ISSUE TITLE
whoami, ipconfig broken

### ISSUE THREAD

**Issue by friedrico** [packetfu/packetfu#206]
## Steps to reproduce

How'd you do it?
```ruby
# root permissions
require 'packetfu'
include PacketFu
Utils.ifconfig("tap0")
=> {:iface=>"tap0:"}
Utils.ifconfig("eth0")
=> {:iface=>"eth0:"

Utils.whoami?
=> {:iface=>"eth0", :pcapfile=>"/tmp/out.pcap", :eth_saddr=>"somehing", :eth_src=>"\xaaa...aa", :ip_saddr=>"someip", :ip_src=>123456789, :ip_src_bin=>"\xdeadbeef", :eth_dst=>"\xa...aaaaa", :eth_daddr=>"something"}

Utils.whoami?({:iface=>"tap0"})
Traceback (most recent call last):
        6: from /usr/bin/irb:23:in `<main>'
        5: from /usr/bin/irb:23:in `load'
        4: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        3: from (irb):18
        2: from /var/lib/gems/2.7.0/gems/packetfu-1.1.13/lib/packetfu/utils.rb:140:in `whoami?'
        1: from /var/lib/gems/2.7.0/gems/packetfu-1.1.13/lib/packetfu/utils.rb:171:in `rescue in whoami?'
SocketError (Didn't receive the whoami() packet, can't automatically configure.)


%x"ifconfig tap0".split(/[\s]*\n[\s]*/).first =~ /[\s]HWaddr[\s]+([0-9a-fA-F:]{17})/i
=>nil
%x"ifconfig tap0".split(/[\s]*\n[\s]*/).first
=> "tap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500"
# makes sense
```

## Expected behavior

What should happen?
print the interface parameters
## Current behavior
doesnt do shit

What happens instead?
shit

## System stuff
```
ifconfig # kali
tap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 123.123.123.123  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::aa:aa:fe1e:aaaaaa  prefixlen 64  scopeid 0x20<link>
        ether aa:bb:cc:dd:ee:ff  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 2 (2.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 5 (1.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
### Versions

- Ruby Version (ruby -v): ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu] 
- and: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
- PacketFu Version (gem list|grep packetfu -or- git log -1): packetfu (1.1.13)
- OS Version: `Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-1kali1 (2021-06-25) x86_64 GNU/Linux`
- and: `Linux host 5.14.11-arch1-1 #1 SMP PREEMPT Sun, 10 Oct 2021 00:48:26 +0000 x86_64 GNU/Linux`

### I installed PacketFu from:
- [ ] Git Source
- [x] Gem

it seems the parser is not adequate?

**Comment by 4zv4l** [comment]
I wish it can be fixed too, I also have issues with `ifconfig`
