### ISSUE TITLE
Figure out why specs don't pass on Mac OSX w/ Wireless Interface

### ISSUE THREAD

**Issue by claudijd** [packetfu/packetfu#54]
I tried running specs when my default interface was "en1" (wireless) on OSX, but it fails due to interface selection issues.  This is likely related in some fashion to the same problem we fixed in #43

Here's my result:

rvmsudo ruby all_tests.rb

Testing PacketFu v1.1.11
    Running test_arp.rb...
    test_arp.rb: All passed
    Running test_capture.rb...
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:104: warning: unable to get IP: en0: no IPv4 address assigned
    Are you sure you're root? Error: File: test_capture.rb had failures or errors:
    --------------------------------------------------------------------------------
    Run options: 

    # Running tests:

    ..F.FF

    Finished tests in 26.154825s, 0.2294 tests/s, 0.2294 assertions/s.

      1) Failure:
    test_filter(CaptureTest) [test_capture.rb:32]:
    Failed assertion, no message given.

      2) Failure:
    test_no_filter(CaptureTest) [test_capture.rb:46]:
    Failed assertion, no message given.

      3) Failure:
    test_whoami(CaptureTest) [test_capture.rb:14]:
    Exception raised:
    <#<RuntimeError: lo: No such device exists (BIOCSETIF failed: Device not configured)>>.

    6 tests, 6 assertions, 3 failures, 0 errors, 0 skips
    --------------------------------------------------------------------------------
    Running test_eth.rb...
    test_eth.rb: All passed
    Running test_hsrp.rb...
    test_hsrp.rb: All passed
    Running test_icmp.rb...
    test_icmp.rb: All passed
    Running test_inject.rb...
    Are you sure you're root? Error: Are you sure you're root? Error: File: test_inject.rb had failures or errors:
    --------------------------------------------------------------------------------
    Run options: 

    # Running tests:

    .EF

    Finished tests in 0.001025s, 2926.8293 tests/s, 2926.8293 assertions/s.

      1) Error:
    test_to_w(InjectTest):
    RuntimeError: lo: No such device exists (BIOCSETIF failed: Device not configured)
        /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:63:in `open_live'
        /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:63:in `capture'
        /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:47:in `setup_params'
        /Users/jclaudius/code/packetfu/lib/packetfu/capture.rb:40:in `initialize'
        /Users/jclaudius/code/packetfu/lib/packetfu/utils.rb:107:in `new'
        /Users/jclaudius/code/packetfu/lib/packetfu/utils.rb:107:in `whoami?'
        test_inject.rb:19:in `test_to_w'

      2) Failure:
    test_whoami(InjectTest) [test_inject.rb:14]:
    Exception raised:
    <#<RuntimeError: lo: No such device exists (BIOCSETIF failed: Device not configured)>>.

    3 tests, 3 assertions, 1 failures, 1 errors, 0 skips
    --------------------------------------------------------------------------------
    Running test_invalid.rb...
    test_invalid.rb: All passed
    Running test_ip.rb...
    test_ip.rb: All passed
    Running test_ip6.rb...
    test_ip6.rb: All passed
    Running test_octets.rb...
    test_octets.rb: All passed
    Running test_packet.rb...
    test_packet.rb: All passed
    Running test_pcap.rb...
    test_pcap.rb: All passed
    Running test_structfu.rb...
    test_structfu.rb: All passed
    Running test_tcp.rb...
    test_tcp.rb: All passed
    Running test_udp.rb...
    test_udp.rb: All passed

**Comment by claudijd** [comment]
No longer an issue.
